######################################################################################################
# This file is generated when `botfront up` is invoked.                                              #
# Changes in .botfront/botfront.yml and .botfront/docker-compose-template.yml will be reflected here #
######################################################################################################

version: '3.0'
services:
  botfront:
    image: 'sofa566/botfront:v1.0.6b'
    container_name: botfront-app
    restart: always
    networks:
      - botfront-network
    volumes:
      - './models/:/app/models'
    ports:
      - '8888:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      PORT: 3000
  rasa:
    build:
      context: ./rasa
      args:
        RASA_IMAGE: '${IMAGES_CURRENT_RASA}'
    container_name: botfront-rasa
    networks:
      - botfront-network
    restart: always
    ports:
      - '5005:5005'
    volumes:
      - './models/:/app/models'
    env_file:
      - .env
  actions:
    image: 'sofa566/java-action-server:1.0.1'
    container_name: botfront-actions
    networks:
      - botfront-network
    restart: always
    ports:
      - '5055:5055'
    command:
      - java
      - -noverify
      - -XX:TieredStopAtLevel=1
      - -cp
      - app:app/lib/*
      - io.github.rbajek.rasa.action.server.RasaActionServer
    env_file:
      - .env
  duckling:
    image: 'botfront/duckling:latest'
    container_name: botfront-duckling
    networks:
      - botfront-network
    restart: always
    ports:
      - '8000:8000'
  mongo:
    image: 'mongo:latest'
    container_name: botfront-mongo
    restart: always
    networks:
      - botfront-network
    volumes:
      - './botfront-db:/data/db'
    ports:
      - '27017:27017'
    env_file:
      - .env
networks:
  botfront-network: {}
volumes:
  botfront-db: null
